# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  DOCKER_IMAGE_ORIGIN: "docker.pkg.github.com/ssharshunov/chaos_calmer/openwrt_build"
  DOCKER_IMAGE_VERSION: "1.1"
  REPOSITORY: "chaos_calmer"
  IN_DOCKER_ROOT_FOLDER: "/src/chaos_calmer"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    name: ${{ matrix.chip.name }}
    
    strategy:
      fail-fast: false
      matrix:
        chip:
          - name: 📦hi3520dv200
            SOC: hi3520dv200
            artifact: hi3520dv200.tar.xz
            kernel: "3.0.8"
            profile: "20dv200_sergek"
            ker_config: "ker_config_ser_02"
            wrt_config: "wrt_config_ser_02"
#           - name: 📦hi3518ev200
#             SOC: hi3518ev200
#             artifact: hi3518ev200.tar.xz
#             kernel: "3.4.35"
#             profile: "18ev200_sergek"
#             ker_config: "ker_config_ser_01"
#             wrt_config: "wrt_config_ser_01"

#           - name: 📦hi3516cv200
#             SOC: hi3516cv200
#             artifact: hi3516cv200.tar.xz

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Create dl folder
      run: mkdir ${PWD}/dl
      
    - name: Cache DL
      id: cache-dl
      uses: actions/cache@v1
      with:
        path: dl
        key: chaos_calmer_dl
      
    - name: Login to docker registry
      id: login_reg
      run: |
        # Login to GitHub Packages and build Docker image
        docker login docker.pkg.github.com -u ssharshunov -p ${GITHUB_TOKEN}
        docker pull ${DOCKER_IMAGE_ORIGIN}:${DOCKER_IMAGE_VERSION}
        
    - name: Clone source code
      env:
        REPO_URL: https://github.com/OpenIPC/chaos_calmer
        REPO_BRANCH: feature/zigfisher_current_work
      run: git clone --depth 1 ${REPO_URL} -b ${REPO_BRANCH} ${REPOSITORY}
      
    - name: Prepare openwrt
      id: prepare
      run: |
        echo ${{ matrix.chip.profile }} > ${REPOSITORY}/target/linux/hi35xx/base-files/etc/soc-version
        ls -la chaos_calmer
        ls -la ${PWD}
        wget https://raw.githubusercontent.com/SSharshunov/chaos_calmer/master/${{ matrix.chip.wrt_config }} -O ${REPOSITORY}/target/linux/hi35xx/examples/.config_18ev200_zftlab_rotek
        wget https://raw.githubusercontent.com/SSharshunov/chaos_calmer/master/${{ matrix.chip.ker_config }} -O ${REPOSITORY}/target/linux/hi35xx/config-${{ matrix.chip.kernel }}
        sed -i "s/KERNEL_PATCHVER:=.*/KERNEL_PATCHVER:=${{ matrix.chip.kernel }}/" ${REPOSITORY}/target/linux/hi35xx/Makefile
        echo "::set-output name=status::success"
        
    - name: Config
      id: config
      run: |
        run: |
        docker run -v ${PWD}/dl:${IN_DOCKER_ROOT_FOLDER}/dl -v ${PWD}/${REPOSITORY}:${IN_DOCKER_ROOT_FOLDER}/ --rm -i ${DOCKER_IMAGE_ORIGIN}:${DOCKER_IMAGE_VERSION} \
          bash -c "ls -la ${IN_DOCKER_ROOT_FOLDER}/dl && cd ${IN_DOCKER_ROOT_FOLDER} && cp target/linux/hi35xx/examples/.config_18ev200_zftlab_rotek ./.config && ./scripts/feeds update glutinium openipc"
        echo "::set-output name=status::success"
        
    - name: Download pack
      id: download_packages
      run: |
        docker run -v ${PWD}/dl:${IN_DOCKER_ROOT_FOLDER}/dl -v ${PWD}/${REPOSITORY}:${IN_DOCKER_ROOT_FOLDER}/ --rm -i ${DOCKER_IMAGE_ORIGIN}:${DOCKER_IMAGE_VERSION} \
          bash -c "cd ${IN_DOCKER_ROOT_FOLDER} && time make download"
        echo "::set-output name=status::success"
            
    - name: Build
      id: compile
#       if: steps.compile.download_packages.status == 'success'
      run: |
        docker run -v ${PWD}/dl:${IN_DOCKER_ROOT_FOLDER}/dl -v ${PWD}/${REPOSITORY}:${IN_DOCKER_ROOT_FOLDER}/ --rm -i ${DOCKER_IMAGE_ORIGIN}:${DOCKER_IMAGE_VERSION} \
          bash -c "ls -la ${IN_DOCKER_ROOT_FOLDER}/dl && cd ${IN_DOCKER_ROOT_FOLDER} && time make V=s -j$(nproc) "
        echo "::set-output name=status::success"
          
    - name: Upload bin directory
      uses: actions/upload-artifact@master
      if: steps.compile.outputs.status == 'success'
      with:
        name: ${{ matrix.chip.artifact }}
        path: chaos_calmer/bin/
        
    - name: Archive images
      run: |
        tar -cJf ${{ matrix.chip.artifact }} chaos_calmer/bin/
#        zip --junk-paths chaos_calmer/bin/ ${{ matrix.chip.artifact }}
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ matrix.chip.artifact }}_images-${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./${{ matrix.chip.artifact }}
        asset_name: ${{ matrix.chip.artifact }}
        asset_content_type: application/x-gtar
          
          

    - name: Create GitHub release with artifacts
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          chaos_calmer/bin/
        name: "Build ${GITHUB_SHA}"
